### ISSUE TITLE
Build error on 6.11.x

### ISSUE THREAD

**Issue by jayjwa** [JohnForecast/LinuxDECnet#9]
The kmod fails to build on newer kernels.
```
Log of make -C /lib/modules/6.11.3/build M=/usr/src/decnet3/LinuxDECnet/kernel 
Mon Oct 14 12:58:39 2024

make: Entering directory '/usr/src/linux-6.11.3'
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_dev.o
/usr/src/decnet3/LinuxDECnet/kernel/dnet_dev.c:315:12: warning: no previous prototype for ‘dn_dev_init’ [-Wmissing-prototypes]
  315 | int __init dn_dev_init(void)
      |            ^~~~~~~~~~~
/usr/src/decnet3/LinuxDECnet/kernel/dnet_dev.c:436:13: warning: no previous prototype for ‘dn_dev_exit’ [-Wmissing-prototypes]
  436 | void __exit dn_dev_exit(void)
      |             ^~~~~~~~~~~
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_next.o
/usr/src/decnet3/LinuxDECnet/kernel/dnet_next.c:256:6: warning: no previous prototype for ‘dn_next_remove’ [-Wmissing-prototypes]
  256 | void dn_next_remove(
      |      ^~~~~~~~~~~~~~
/usr/src/decnet3/LinuxDECnet/kernel/dnet_next.c:518:12: warning: no previous prototype for ‘dn_next_init’ [-Wmissing-prototypes]
  518 | int __init dn_next_init(void)
      |            ^~~~~~~~~~~~
/usr/src/decnet3/LinuxDECnet/kernel/dnet_next.c:576:13: warning: no previous prototype for ‘dn_next_cleanup’ [-Wmissing-prototypes]
  576 | void __exit dn_next_cleanup(void)
      |             ^~~~~~~~~~~~~~~
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_node.o
/usr/src/decnet3/LinuxDECnet/kernel/dnet_node.c: In function ‘dn_node_scan’:
/usr/src/decnet3/LinuxDECnet/kernel/dnet_node.c:141:76: warning: suggest braces around empty body in an ‘if’ statement [-Wempty-body]
  141 |                                                         /*** Log event ***/;
      |                                                                            ^
/usr/src/decnet3/LinuxDECnet/kernel/dnet_node.c: At top level:
/usr/src/decnet3/LinuxDECnet/kernel/dnet_node.c:154:6: warning: no previous prototype for ‘dn_node_timeout’ [-Wmissing-prototypes]
  154 | void dn_node_timeout(
      |      ^~~~~~~~~~~~~~~
/usr/src/decnet3/LinuxDECnet/kernel/dnet_node.c:307:12: warning: no previous prototype for ‘dn_node_init’ [-Wmissing-prototypes]
  307 | int __init dn_node_init(void)
      |            ^~~~~~~~~~~~
/usr/src/decnet3/LinuxDECnet/kernel/dnet_node.c:350:13: warning: no previous prototype for ‘dn_node_cleanup’ [-Wmissing-prototypes]
  350 | void __exit dn_node_cleanup(void)
      |             ^~~~~~~~~~~~~~~
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_nsp.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_route.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_sock.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_sys.o
/usr/src/decnet3/LinuxDECnet/kernel/dnet_sys.c:203:33: error: initialization of ‘int (*)(const struct ctl_table *, int,  void *, size_t *, loff_t *)’ {aka ‘int (*)(const struct ctl_table *, int,  void *, long unsigned int *, long long int *)’} from incompatible pointer type ‘int (*)(struct ctl_table *, int,  void *, size_t *, loff_t *)’ {aka ‘int (*)(struct ctl_table *, int,  void *, long unsigned int *, long long int *)’} [-Wincompatible-pointer-types]
  203 |                 .proc_handler = dn_node_address_handler,
      |                                 ^~~~~~~~~~~~~~~~~~~~~~~
/usr/src/decnet3/LinuxDECnet/kernel/dnet_sys.c:203:33: note: (near initialization for ‘dn_table[0].proc_handler’)
make[2]: *** [scripts/Makefile.build:244: /usr/src/decnet3/LinuxDECnet/kernel/dnet_sys.o] Error 1
make[1]: *** [/usr/src/linux-6.11.3/Makefile:1926: /usr/src/decnet3/LinuxDECnet/kernel] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-6.11.3'
make exited with status code 2

Mon Oct 14 12:58:46 2024
----------------

```
Kernel 6.11.3 and gcc-14.2.0.

**Comment by JohnForecast** [comment]
Try the latest code. I don't have a system with kernel 6.11.x or gcc 14.2 but I have tested that it still builds on kernel 6.6.31 and gcc 12.2.

**Comment by jayjwa** [comment]
Sorry for the late response. My eyes saw "6.1.1" for some reason, which was puzzling. 
 
```
Log of make -C /lib/modules/6.11.3/build M=/usr/src/decnet3/LinuxDECnet/kernel 
Mon Oct 21 13:31:19 2024

make: Entering directory '/usr/src/linux-6.11.3'
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_dev.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_next.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_node.o
/usr/src/decnet3/LinuxDECnet/kernel/dnet_node.c:350:13: warning: no previous prototype for ‘dn_node_cleanup’ [-Wmissing-prototypes]
  350 | void __exit dn_node_cleanup(void)
      |             ^~~~~~~~~~~~~~~
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_nsp.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_route.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_sock.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_sys.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_timr.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_trc.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet.o
/usr/src/decnet3/LinuxDECnet/kernel/dnet.c:77:25: error: initialization of ‘int (*)(struct socket *, struct socket *, struct proto_accept_arg *)’ from incompatible pointer type ‘int (*)(struct socket *, struct socket *, int,  bool)’ {aka ‘int (*)(struct socket *, struct socket *, int,  _Bool)’} [-Wincompatible-pointer-types]
   77 |         .accept =       dn_accept,
      |                         ^~~~~~~~~
/usr/src/decnet3/LinuxDECnet/kernel/dnet.c:77:25: note: (near initialization for ‘dnet_proto_ops.accept’)
/usr/src/decnet3/LinuxDECnet/kernel/dnet.c:1805:5: warning: no previous prototype for ‘dnet_zero_write’ [-Wmissing-prototypes]
 1805 | int dnet_zero_write(
      |     ^~~~~~~~~~~~~~~
/usr/src/decnet3/LinuxDECnet/kernel/dnet.c:1939:13: warning: no previous prototype for ‘dnet_exit’ [-Wmissing-prototypes]
 1939 | void __exit dnet_exit(void)
      |             ^~~~~~~~~
make[2]: *** [scripts/Makefile.build:244: /usr/src/decnet3/LinuxDECnet/kernel/dnet.o] Error 1
make[1]: *** [/usr/src/linux-6.11.3/Makefile:1926: /usr/src/decnet3/LinuxDECnet/kernel] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-6.11.3'
make exited with status code 2

Mon Oct 21 13:31:29 2024
----------------
```
6.6.51 is the farthest I've seen it go (which was my old kernel). I don't expect you to chase every kernel as it continues its march ever-onward, but Slackware is already up to 6.11.x and waiting to upgrade causes more changes to deal with when the inevitable change has to come.

**Comment by jayjwa** [comment]
Closer. 
```
Log of make -C /lib/modules/6.11.3/build M=/usr/src/decnet3/LinuxDECnet/kernel 
Tue Oct 22 12:54:33 2024

make: Entering directory '/usr/src/linux-6.11.3'
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_dev.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_next.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_node.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_nsp.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_route.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_sock.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_sys.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_timr.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_trc.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet.o
/usr/src/decnet3/LinuxDECnet/kernel/dnet.c: In function ‘dn_accept’:
/usr/src/decnet3/LinuxDECnet/kernel/dnet.c:750:21: error: ‘args’ undeclared (first use in this function); did you mean ‘arg’?
  750 |         bool kern = args->kern;
      |                     ^~~~
      |                     arg
/usr/src/decnet3/LinuxDECnet/kernel/dnet.c:750:21: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [scripts/Makefile.build:244: /usr/src/decnet3/LinuxDECnet/kernel/dnet.o] Error 1
make[1]: *** [/usr/src/linux-6.11.3/Makefile:1926: /usr/src/decnet3/LinuxDECnet/kernel] Error 2
make: *** [Makefile:224: __sub-make] Error 2
make: Leaving directory '/usr/src/linux-6.11.3'
make exited with status code 2

Tue Oct 22 12:54:43 2024
----------------
```
Is the solution as the compiler suggests?

**Comment by JohnForecast** [comment]
Typo in my last fix/ Shopuld be OK now.

**Comment by jayjwa** [comment]
Something's not quite right. Linux (1.1) can connect outward, but is invisible to everyone else on the network. There's some errors regarding /proc as well. The kmod does build and install proper. dnetd will not start. 

```
root@atr2 LinuxDECnet/kernel # make -C /lib/modules/`uname -r`/build M=$PWD 
make: Entering directory '/usr/src/linux-6.11.3'
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_dev.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_next.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_node.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_nsp.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_route.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_sock.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_sys.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_timr.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet_trc.o
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/dnet.o
  LD [M]  /usr/src/decnet3/LinuxDECnet/kernel/decnet3.o
  MODPOST /usr/src/decnet3/LinuxDECnet/kernel/Module.symvers
  CC [M]  /usr/src/decnet3/LinuxDECnet/kernel/decnet3.mod.o
  LD [M]  /usr/src/decnet3/LinuxDECnet/kernel/decnet3.ko
make: Leaving directory '/usr/src/linux-6.11.3'
root@atr2 LinuxDECnet/kernel # make -C /lib/modules/`uname -r`/build M=$PWD modules_install
make: Entering directory '/usr/src/linux-6.11.3'
  INSTALL /lib/modules/6.11.3/updates/decnet3.ko
  ZSTD    /lib/modules/6.11.3/updates/decnet3.ko.zst
  DEPMOD  /lib/modules/6.11.3
make: Leaving directory '/usr/src/linux-6.11.3'
root@atr2 LinuxDECnet/kernel # rc.decnet start                                                                     
%DECNET-I-INIT, Linux DECnet control switch
/proc/sys/net/decnet/node_address missing, is DECnet module loaded?
%DECNET-I-INIT, Linux DECnet services not able to start

2024-10-22T20:01:10.800437-04:00 atr2 kernel: DECnet Ethernet Endnode for Linux V3.0.10 (C) 2023 John Forecast
2024-10-22T20:01:10.800457-04:00 atr2 kernel: DECnet: Phase IV, started on br0
2024-10-22T20:01:10.800468-04:00 atr2 kernel: DECnet: Nexthop cache hash table of 4096 buckets, 64 Kbytes
2024-10-22T20:01:10.803174-04:00 atr2 kernel: DECnet: Node database hash table of 4096 buckets, 64 Kbytes
2024-10-22T20:01:10.803199-04:00 atr2 kernel: NET: Registered PF_DECnet protocol family
2024-10-22T20:01:10.804760-04:00 atr2 kernel: sysctl table check failed: net/decnet/(null) procname is null
2024-10-22T20:01:10.804777-04:00 atr2 kernel: sysctl table check failed: net/decnet/(null) No proc_handler

Module loaded:
decnet3                73728  2

NCP>loop node 1.2
20:08:22        NCP
                Request # 146 Accepted
NCP>
20:08:23        NCP

Request # 146; Loop Node Completed
NCP>loop node 1.1
20:08:41        NCP
                Request # 147 Accepted
NCP>
20:09:40        NCP

Request # 147; Loop Node Failed, Mirror connect failed

Remote Node = 1.1 (ATR2)

 Unlooped count = 29793

NCP>
```
There info in /proc, but no node_address.

```
jayjwa@atr2 /tmp> cat /proc/net/decnet_nodes 
1.19    1   1257        0x00000bb6 0x0000017a 0x00000049 0x0000005a 0x00000d16 0x000008cb 0x000000aa 0x000000aa 0x0000 0x0001 0x0000
1.11    1   458         0x00000c05 0x000002c3 0x00000025 0x00000011 0x00000cc6 0x00000432 0x00000039 0x00000022 0x0000 0x0001 0x0000
1.1     0   1389        0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x000000e0 0x00000000 0x00000008 0x0000 0x0002 0x0006
```
```
jayjwa@atr2 /tmp> ls /proc/net/decnet*
/proc/net/decnet        /proc/net/decnet_dev    /proc/net/decnet_phase
/proc/net/decnet_cache  /proc/net/decnet_neigh  /proc/net/decnet_revision
/proc/net/decnet_cost   /proc/net/decnet_nodes  /proc/net/decnet_zero_node

jayjwa@atr2 /tmp> cat /proc/net/decnet_dev
Name     Flags T1   Timer1 T3   Timer3 T4   Timer4 BlkSize Pri State DevType    Router Peer
lo       B     0000 0000   0000 0000   0000 0000   65533   000 00    loopback                  
br0      B     0000 0000   0006 0010   0000 0000   1498    000 00    ethernet
```
This worked previously so maybe something changed in /proc. Actually, there's nothing about DECnet in /proc/sys/net at all. 
```
jayjwa@atr2 /tmp> ls /proc/sys/net/
bridge/  ipv4/  mptcp/      nf_conntrack_max  unix/
core/    ipv6/  netfilter/  sctp/

jayjwa@atr2 /tmp [SIGINT]> cat /etc/modprobe.d/decnet3.conf
# DECnet for Linux

# The area and node that we are using
options decnet3 dn_nodeaddr=1.1
 
# Our nodename
options decnet3 dn_nodename=atr2

# Which device to attach to? 
options decnet3 dn_ifname=br0

#EOF
```

**Comment by JohnForecast** [comment]
The error:
    /proc/sys/net/decnet/node_address missing, is DECnet module loaded?

indicates that dnetd has exited so incoming connections will not be processed. I'll try to take a look at this tomorrow although I may not have much time for the next couple of days.

**Comment by JohnForecast** [comment]
Kernel 6.10 changed how to calculate the length of the sysctl tables. I've updated dnet_sys.c to accomodate this change. Can you try again?

**Comment by jayjwa** [comment]
This seems to have fixed the issue.
